(cl:defpackage whycon-srv
  (:use )
  (:export
   "SETNUMBEROFTARGETS"
   "<SETNUMBEROFTARGETS-REQUEST>"
   "SETNUMBEROFTARGETS-REQUEST"
   "<SETNUMBEROFTARGETS-RESPONSE>"
   "SETNUMBEROFTARGETS-RESPONSE"
  ))

