// Generated by gencpp from file whycon/SetNumberOfTargetsRequest.msg
// DO NOT EDIT!


#ifndef WHYCON_MESSAGE_SETNUMBEROFTARGETSREQUEST_H
#define WHYCON_MESSAGE_SETNUMBEROFTARGETSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace whycon
{
template <class ContainerAllocator>
struct SetNumberOfTargetsRequest_
{
  typedef SetNumberOfTargetsRequest_<ContainerAllocator> Type;

  SetNumberOfTargetsRequest_()
    : number(0)
    , threshold(0)  {
    }
  SetNumberOfTargetsRequest_(const ContainerAllocator& _alloc)
    : number(0)
    , threshold(0)  {
  (void)_alloc;
    }



   typedef int64_t _number_type;
  _number_type number;

   typedef int64_t _threshold_type;
  _threshold_type threshold;




  typedef boost::shared_ptr< ::whycon::SetNumberOfTargetsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::whycon::SetNumberOfTargetsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetNumberOfTargetsRequest_

typedef ::whycon::SetNumberOfTargetsRequest_<std::allocator<void> > SetNumberOfTargetsRequest;

typedef boost::shared_ptr< ::whycon::SetNumberOfTargetsRequest > SetNumberOfTargetsRequestPtr;
typedef boost::shared_ptr< ::whycon::SetNumberOfTargetsRequest const> SetNumberOfTargetsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::whycon::SetNumberOfTargetsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::whycon::SetNumberOfTargetsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace whycon

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'whycon': ['/home/lekhraj/catkin_ws/src/whycon/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::whycon::SetNumberOfTargetsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::whycon::SetNumberOfTargetsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::whycon::SetNumberOfTargetsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::whycon::SetNumberOfTargetsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::whycon::SetNumberOfTargetsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::whycon::SetNumberOfTargetsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::whycon::SetNumberOfTargetsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "110202b35d9b2f547e6475584cfb396e";
  }

  static const char* value(const ::whycon::SetNumberOfTargetsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x110202b35d9b2f54ULL;
  static const uint64_t static_value2 = 0x7e6475584cfb396eULL;
};

template<class ContainerAllocator>
struct DataType< ::whycon::SetNumberOfTargetsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "whycon/SetNumberOfTargetsRequest";
  }

  static const char* value(const ::whycon::SetNumberOfTargetsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::whycon::SetNumberOfTargetsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 number\n\
int64 threshold\n\
";
  }

  static const char* value(const ::whycon::SetNumberOfTargetsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::whycon::SetNumberOfTargetsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.number);
      stream.next(m.threshold);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetNumberOfTargetsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::whycon::SetNumberOfTargetsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::whycon::SetNumberOfTargetsRequest_<ContainerAllocator>& v)
  {
    s << indent << "number: ";
    Printer<int64_t>::stream(s, indent + "  ", v.number);
    s << indent << "threshold: ";
    Printer<int64_t>::stream(s, indent + "  ", v.threshold);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WHYCON_MESSAGE_SETNUMBEROFTARGETSREQUEST_H
