// Generated by gencpp from file whycon/SetNumberOfTargetsResponse.msg
// DO NOT EDIT!


#ifndef WHYCON_MESSAGE_SETNUMBEROFTARGETSRESPONSE_H
#define WHYCON_MESSAGE_SETNUMBEROFTARGETSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace whycon
{
template <class ContainerAllocator>
struct SetNumberOfTargetsResponse_
{
  typedef SetNumberOfTargetsResponse_<ContainerAllocator> Type;

  SetNumberOfTargetsResponse_()
    : targets(0)  {
    }
  SetNumberOfTargetsResponse_(const ContainerAllocator& _alloc)
    : targets(0)  {
  (void)_alloc;
    }



   typedef int64_t _targets_type;
  _targets_type targets;




  typedef boost::shared_ptr< ::whycon::SetNumberOfTargetsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::whycon::SetNumberOfTargetsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetNumberOfTargetsResponse_

typedef ::whycon::SetNumberOfTargetsResponse_<std::allocator<void> > SetNumberOfTargetsResponse;

typedef boost::shared_ptr< ::whycon::SetNumberOfTargetsResponse > SetNumberOfTargetsResponsePtr;
typedef boost::shared_ptr< ::whycon::SetNumberOfTargetsResponse const> SetNumberOfTargetsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::whycon::SetNumberOfTargetsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::whycon::SetNumberOfTargetsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace whycon

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'whycon': ['/home/lekhraj/catkin_ws/src/whycon/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::whycon::SetNumberOfTargetsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::whycon::SetNumberOfTargetsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::whycon::SetNumberOfTargetsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::whycon::SetNumberOfTargetsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::whycon::SetNumberOfTargetsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::whycon::SetNumberOfTargetsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::whycon::SetNumberOfTargetsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c4b30573202f471f13445ea520b70452";
  }

  static const char* value(const ::whycon::SetNumberOfTargetsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc4b30573202f471fULL;
  static const uint64_t static_value2 = 0x13445ea520b70452ULL;
};

template<class ContainerAllocator>
struct DataType< ::whycon::SetNumberOfTargetsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "whycon/SetNumberOfTargetsResponse";
  }

  static const char* value(const ::whycon::SetNumberOfTargetsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::whycon::SetNumberOfTargetsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 targets\n\
\n\
";
  }

  static const char* value(const ::whycon::SetNumberOfTargetsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::whycon::SetNumberOfTargetsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.targets);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetNumberOfTargetsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::whycon::SetNumberOfTargetsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::whycon::SetNumberOfTargetsResponse_<ContainerAllocator>& v)
  {
    s << indent << "targets: ";
    Printer<int64_t>::stream(s, indent + "  ", v.targets);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WHYCON_MESSAGE_SETNUMBEROFTARGETSRESPONSE_H
